### ISSUE TITLE
libgsl dependency conflict on xenial due to r-cran-rcppziggurat

### ISSUE THREAD

**Issue by zeehio** [marutter/CRAN-PPA#1]
Hi Michael, thank you for your work on the PPA repository. I hope this is a nice way of contacting you.

The rcppgsl package built here https://launchpadlibrarian.net/448752123/buildlog_ubuntu-xenial-amd64.rcppgsl_0.3.7-1cran1ppa0_BUILDING.txt.gz depends on libgsl23, not available in xenial.

Could you rebuild it with libgsl2? Or provide libgsl23?

Otherwise I fail to install it on Travis.

**Comment by zeehio** [comment]
The installation fails when both r-cran-rcppgsl and  r-cran-rcppzigurat are going to be installed. See https://github.com/zeehio/test1 for a minimum working example

**Comment by marutter** [comment]
I can't recreate this issue on my machine. libgsl23 and r-cran-rcppgsl install without any issues on my local chroot.  I do provide "gsl" on c2d4u3.5, so it should be downloading from there.  This sounds like a Travis issue, which I am not familiar enough to help with.

**Comment by zeehio** [comment]
Thank you for your answer. The installation fails with `apt-get install r-cran-rcppgsl r-cran-rcppzigurat`. I will test again later on a docker Ubuntu xenial image, out of Travis, and confirm this.

Rfast fails to build on Ubuntu xenial on launchpad for the same reason, log https://launchpadlibrarian.net/451875888/buildlog_ubuntu-xenial-amd64.rfast_1.9.6-1cran1ppa0_BUILDING.txt.gz

So probably the issue is that r-cran-rcppziggurat needs to be rebuilt

**Comment by zeehio** [comment]
## Error when installing `r-cran-rcppziggurat` on Ubuntu xenial

`apt install r-cran-rcppziggurat`

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 r-cran-rcppziggurat : Depends: libgsl2 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

## Details:

### ` r-cran-rcppziggurat` directly depends on `r-cran-rcppgsl` and  `libgsl2` 

`apt show r-cran-rcppziggurat`
```
Package: r-cran-rcppziggurat
Version: 0.1.5-1cran1ppa0
...
Maintainer: cran2deb4ubuntu <cran2deb4ubuntu@gmail.com>
...
Depends: r-base-core, r-cran-rcpp, r-cran-rcppgsl, libc6 (>= 2.14), libgcc1 (>= 1:3.0), libgsl2, libstdc++6 (>= 5.2)
APT-Sources: http://ppa.launchpad.net/marutter/c2d4u3.5/ubuntu xenial/main amd64 Packages
Description: GNU R package "'Rcpp' Integration of Different "Ziggurat"
```

### ` r-cran-rcppgsl` directly depends on  `libgsl23 (>= 2.5)`
`apt show  r-cran-rcppgsl`

```
Package: r-cran-rcppgsl
Version: 0.3.7-1cran1ppa0
Maintainer: cran2deb4ubuntu <cran2deb4ubuntu@gmail.com>
Depends: r-cran-rcpp, r-base-core, libc6 (>= 2.14), libgcc1 (>= 1:3.0), libgsl23 (>= 2.5), libstdc++6 (>= 5.2)
APT-Sources: http://ppa.launchpad.net/marutter/c2d4u3.5/ubuntu xenial/main amd64 Packages
```

### `libgsl23` and `libgsl2` can't be installed at the same time

`apt install libgsl2 libgsl23`

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgsl23 : Depends: libgslcblas0 (= 2.5+dfsg-6~ubuntu16.04.1~ppa1) but it is not going to be installed
```

`apt install libgsl2 libgslcblas0`

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgslcblas0 : Conflicts: libgsl2 but 2.1+dfsg-2 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by zeehio** [comment]
As far as I can understand this, rebuilding `r-cran-rcppziggurat` with `libgsl23` would fix the issue.

**Comment by marutter** [comment]
The issue was with rcppziggurat, not cppgsl.  Sorry about the confusion.  I have rebuilt rcppziggurat and it now installs.
